### ISSUE TITLE
Scrcpy won't start

### ISSUE THREAD

**Issue by KibSquib48** [yume-chan/ya-webadb#476]
### Issue Checklist

- [X] I'm using the library programmatically

### Library version

unsure

### Runtime

Chrome OS 108.0.5359.172

### Device

Pixel 6, Android 13 QPR2 Beta 2

### Describe the bug

Scrcpy won't start, it was working last week but today it started giving me this error:
`TypeError: Class constructor N cannot be invoked without 'new'
    at eZ (https://yume-chan.github.io/ya-webadb/_next/static/chunks/pages/_app-d4b91575b6ce4c64.js:1:440465)
    at new ObservableObject.key (https://yume-chan.github.io/ya-webadb/_next/static/chunks/pages/_app-d4b91575b6ce4c64.js:1:440039)
    at Object.start [as onClick] (https://yume-chan.github.io/ya-webadb/_next/static/chunks/pages/scrcpy-1e5b3d21a8ec1517.js:1:35089)`

### Steps to reproduce

1. Connect device
2. Start scrcpy

**Comment by yume-chan** [comment]
Thanks for the report!
