### ISSUE TITLE
Scrcpy fails to connect to device

### ISSUE THREAD

**Issue by miltoid19** [yume-chan/ya-webadb#479]
### Issue Checklist

- [X] I'm using the library programmatically

### Library version

v0.0.17 Latest

### Runtime

Windows 11 Version 22H2 (Build 22622.575), Vivaldi 5.6.2867.62 (Stable channel) (64-bit) 

### Device

Poco F3

### Describe the bug

Hello, I tired to look if someone was facing similar problems to mine but I did not manage to find any. 
Essentially starting scrcpy fails with the following log 
> [client] Server version: 1.24
[client] Server arguments: log_level=debug max_size=1080 bit_rate=4000000 lock_video_orientation=-1 crop= power_on=true decoder=webcodecs send_device_meta=false send_dummy_byte=false
[server] WARN: Unknown server option: decoder
[server] INFO: Device: Xiaomi M2012K11AG (Android 13)
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2103)
	at java.lang.Class.getMethod(Class.java:1724)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
	at com.genymobile.scrcpy.Device.<init>(Device.java:103)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
	at com.genymobile.scrcpy.Server.main(Server.java:335)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'
[client] Video size changed: 488x1080

I don't really seem to understand what the problem is though. Any help would be very appreciated.

### Steps to reproduce

Connecting the device works fine when it requests authentication of the USB debug pair.

**Comment by yume-chan** [comment]
Related to https://github.com/Genymobile/scrcpy/issues/3497

Released version 0.0.18 with support for Scrcpy server version 1.25.
