### ISSUE TITLE
Error: Path too long [Scrcpy]

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#513]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb
- [x] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Runtime

chromeOS 110 and windows 10

### Device

Samsung galaxy A53 5G android 12

### Describe the bug

when connecting to scrcpy, I get this error
`Error: path too long
    at Object.<anonymous> (https://www.tangoapp.dev/_next/static/chunks/pages/_app-c6a1da9bace4159d.js:1:506061)
    at https://www.tangoapp.dev/_next/static/chunks/pages/_app-c6a1da9bace4159d.js:8:66753
    at async eC (https://www.tangoapp.dev/_next/static/chunks/pages/_app-c6a1da9bace4159d.js:1:506165)
    at async ez (https://www.tangoapp.dev/_next/static/chunks/pages/_app-c6a1da9bace4159d.js:1:509594)
    at async eW (https://www.tangoapp.dev/_next/static/chunks/pages/_app-c6a1da9bace4159d.js:1:510353)
    at async eU.write (https://www.tangoapp.dev/_next/static/chunks/pages/_app-c6a1da9bace4159d.js:1:513681)
    at async eG.pushServer (https://www.tangoapp.dev/_next/static/chunks/pages/scrcpy-21414d9b74b412b6.js:1:23327)
    at async Object.start [as onClick] (https://www.tangoapp.dev/_next/static/chunks/pages/scrcpy-21414d9b74b412b6.js:1:37897)`

### Steps to reproduce

1. connect device
2. start scrcpy
3. 
![image](https://user-images.githubusercontent.com/78228404/223811698-fd2d78dd-1717-4a6a-bb52-bae8634e970b.png)

**Comment by glitch128** [comment]
I think that this might be caused by a recent pr
